version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-postgres
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sensors"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - smarthome-network

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - ".env"
    ports:
      - "8085:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  temperature-api:
    build:
      context: ./temperature_api
      dockerfile: Dockerfile
    container_name: temperature-api
    ports:
      - "8081:8081"
    env_file:
      - "./temperature_api/.env"
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - smarthome-network
  app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
    env_file:
      - ".env"
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - smarthome-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  smarthome-network:
    driver: bridge