version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-postgres
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - smarthome-network

#  temperature-api:
  ## тут нужно добавить приложение

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - ".env"
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
    env_file:
      - ".env"
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - smarthome-network

volumes:
  postgres_data:

networks:
  smarthome-network:
    driver: bridge